apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-service
  labels:
    app: reverseproxy
spec:
  selector:
    app: reverseproxy
  ports:
  - name: "8080" 
    port: 8080
    targetPort: 8080